# Generated by Django 5.0.6 on 2024-06-03 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akun',
            fields=[
                ('user_uid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('identifier', models.EmailField(max_length=254)),
                ('providers', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('signed_in', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Konselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('mitra', models.CharField(max_length=50)),
                ('telepon', models.CharField(max_length=20)),
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_app.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nim', models.CharField(max_length=20)),
                ('universitas', models.CharField(max_length=50)),
                ('telepon', models.CharField(max_length=20)),
                ('akun', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend_app.akun')),
            ],
        ),
        migrations.CreateModel(
            name='Konseling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField()),
                ('persetujuan', models.CharField(max_length=50)),
                ('pertemuan', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('BR', 'Berhenti'), ('DS', 'Disetujui'), ('DT', 'Ditunda')], default='BR', max_length=2)),
                ('konselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.konselor')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pengguna')),
            ],
        ),
        migrations.CreateModel(
            name='Jurnal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pengguna')),
            ],
        ),
    ]
