# Generated by Django 5.0.6 on 2024-06-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akun',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='akun',
            name='signed_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
