# Generated by Django 5.0.6 on 2024-06-16 16:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_app', '0002_alter_akun_created_alter_akun_signed_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengguna',
            name='telepon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='JurnalPagi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('q1', models.CharField(max_length=1000)),
                ('q2', models.CharField(max_length=1000)),
                ('q3', models.CharField(max_length=1000)),
                ('q4', models.CharField(max_length=1000)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pengguna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JurnalSore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('q1', models.CharField(max_length=1000)),
                ('q2', models.CharField(max_length=1000)),
                ('q3', models.CharField(max_length=1000)),
                ('q4', models.CharField(max_length=1000)),
                ('q5', models.CharField(max_length=1000)),
                ('pengguna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_app.pengguna')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Jurnal',
        ),
    ]
